[package]

name = "generic-array"
version = "0.1.0"
authors = [ "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
description = "Generic types implementing functionality of arrays"
license = "MIT"
repository = "https://github.com/fizyk20/generic-array.git"
documentation = "http://fizyk20.github.io/generic-array/generic_array/"

[lib]

name = "generic_array"
crate-type = ["rlib", "dylib"]

[dependencies]
typenum = "1.*"
